import = [
    "~/.config/alacritty/catppuccin_mocha.toml"
]

[window]
padding = { x = 2, y = 5 }

[font]
#normal = { family = "Iosevka Term", style = "Bold" }
normal = { family = "Iosevka Nerd Font", style = "Regular" }
#normal = { family = "MesloLGL Nerd Font", style = "Regular" }
#normal = { family = "CaskaydiaCove Nerd Font", style = "Regular" }
size = 12.0

[env]
TERM = "xterm-256color"
